### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by AlexLeung** [stems/koa-custom-graphiql#1]
When setting up the custom graphiql as Koa middleware as you show in the README, I am getting this error:

```
TypeError: Cannot read property 'request' of undefined
      at getDefaultOptions (C:\...\node_modules\koa-custom-graphiql\lib\middleware.js:38:19)
      at C:\...\node_modules\koa-custom-graphiql\lib\middleware.js:16:23
      at Generator.next (<anonymous>)
      at step (C:\...\node_modules\koa-custom-graphiql\lib\middleware.js:8:191)
      at C:\...\node_modules\koa-custom-graphiql\lib\middleware.js:8:437
      at C:\...\node_modules\koa-custom-graphiql\lib\middleware.js:8:99
      at middleware (C:\...\node_modules\koa-custom-graphiql\lib\middleware.js:30:19)
      at dispatch (C:\...\node_modules\koa-compose\index.js:44:32)
      at next (C:\...\node_modules\koa-compose\index.js:45:18)
      at C:\...\node_modules\koa-router\lib\router.js:326:16
      at dispatch (C:\...\node_modules\koa-compose\index.js:44:32)
      at C:\...\node_modules\koa-compose\index.js:36:12
      at dispatch (C:\...\node_modules\koa-router\lib\router.js:331:31)
      at dispatch (C:\...\node_modules\koa-compose\index.js:44:32)
      at next (C:\...\node_modules\koa-compose\index.js:45:18)
      at bodyParser (C:\...\node_modules\koa-bodyparser\index.js:86:11)
```

I'm using the following package versions:

```
koa: ^2.2.0
koa-body: ^1.6.0
koa-bodyparser: ^4.2.0
koa-router: ^7.1.1
```

Here's what my code looks like:

```js
router.get('/graphiql', graphiql(ctx => {
  return {
    // String of the base URL of the GraphQL endpoint
    // defaults to '/graphql'
    url: '/graphql',

    // specify URLs for your custom GraphiQL (must be hosted, localhost is fine)
    // defaults to the official GraphiQL
    css: '/graphiql.css',
    js: '/graphiql.js',

    // String to display in the query panel
    query: 'query Demo($token: String) { viewer(token: $token) { id } }',

    // Object used to populate the "variables" panel
    variables: {
      token: 'eyJhbGciOiJIUzI1NiJ9.YWNjb3VudFtpZGVd.-w3FiHaq5jIFIOzHErgdEQGvXXG6wClBUDFDVgwUyx8'
    },

    // Object to display in the result panel
    result: {
      data: {
        viewer: { id: 'account[ide]' }
      }
    },
  };
}));
```

**Comment by acarl005** [comment]
@AlexLeung 
This should be fixed in version 1.0.0. I had to make a change to support `koa@2`.

`koa@1` binds the context to `this`, while `koa@2` passes it as an argument. This package now checks for both and should support all versions of koa.

**Comment by AlexLeung** [comment]
Thanks @acarl005. It seems to be displaying although now I'm finding that although the responses show correctly, the SQL queries made are not showing.
![not-showing-sql-queries](https://cloud.githubusercontent.com/assets/5025138/24726679/122aa202-1a08-11e7-8ee7-25ac99e259dd.png)

**Comment by AlexLeung** [comment]
I'm using Apollo Server for the GraphQL endpoint, and the knex sql driver.

**Comment by acarl005** [comment]
Theres one step you have to do. It's kind of burried at the bottom of the [README for graphsiql](https://github.com/acarl005/graphsiql).

You have set a custom header, `x-sql-preview` in the HTTP response. Be careful, when you do so you need to URI-encode any HTTP-unsafe characters.

[Here](https://github.com/stems/join-monster-demo/blob/master/data/fetch.js) is an example of setting it up on the demo. I added some stuff to remove newlines and percent symbols but there may be other characters to watch out for.

**Comment by AlexLeung** [comment]
Thank you!!
![its_alive](https://cloud.githubusercontent.com/assets/5025138/24768873/208dd772-1ab9-11e7-9b54-65fda1072bee.png)

**Comment by AlexLeung** [comment]
I wonder if the GraphiQL maintainers will add in Subscription support anytime soon.

**Comment by acarl005** [comment]
Heh I bet you could write a JS loop that triggers a click event on the ▶️ button. Then it's guaranteed to support IE8!
